### ISSUE TITLE
Data issue

### ISSUE THREAD

**Issue by asc-peter** [ItchyHiker/Irsi_Landmarks#2]
Hello, I'm an independent researcher trying to replicate your model for research purpose.
I cannot get access to your dataset, which requires Baidu account. 
Baidu account recently requires Chinese phone number. 

May I get access to your dataset in other way? 

thanks.

**Comment by ItchyHiker** [comment]
Hi, you can just provide the dataset yourself using the software I mentioned.

**Comment by digital-nomad-cheng** [comment]
> Hello, I'm an independent researcher trying to replicate your model for research purpose.
> I cannot get access to your dataset, which requires Baidu account.
> Baidu account recently requires Chinese phone number.
> 
> May I get access to your dataset in other way?
> 
> thanks.

Hi, you can just prepare the dataset yourself using the software I mentioned.
